name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [9, 10]
        include:
          - php: 8.3
            laravel: 11
          - php: 8.4
            laravel: 11
        exclude:
          - php: 8.2
            laravel: 11
          - laravel: 12

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none # xdebug or pcov

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Run Composer update for Laravel version
        run: |
          if [ "${{ matrix.laravel }}" -eq "9" ]; then
            composer require "orchestra/testbench:^9.0" --no-update --dev --with-all-dependencies --prefer-stable
          elif [ "${{ matrix.laravel }}" -eq "10" ]; then
            composer require "orchestra/testbench:^10.0" --no-update --dev --with-all-dependencies --prefer-stable
          elif [ "${{ matrix.laravel }}" -eq "11" ]; then
            # Pour Laravel 11, on peut avoir besoin de la branche dev de testbench
            # Le "dev-master" pointe vers la branche la plus récente qui supporte L11
            composer require "orchestra/testbench:^11.0" --no-update --dev --with-all-dependencies --prefer-lowest
            # Le --prefer-lowest est CRUCIAL ici pour éviter les versions de testbench qui pointent vers Laravel 13
          fi
          composer update --prefer-dist --no-interaction --no-progress --no-suggest
          
      - name: Run tests
        run: vendor/bin/pest